# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 0355ccdf7b08403a552ea046bf3260e82299fa299a8ac9dd9b41748cc26b1a16131903063289734cca31560f3e3b47f8d82fb01a9b3602ed7b2d95bb1bbd8cd1

test:
  secret_key_base: 1dd78dafd10f89399ed8bfa98bab2788558ce12e39add9a9b2dac38deba237c2efb99ff7d8a89c1d209c4594c57083c1f5cf4b9de1bdf3649b087653fb386f04

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
